import flask, sys, io; app = flask.Flask(__name__); ornek = 'print("Arda Pydroid Sistemine Hos Geldiniz!")\n\nfor i in range(1, 6):\n    print(f"Satir sayisi: {i}")'
@app.route('/')
def ana_sayfa(): return f"""<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Arda Pydroid | Online Python IDE</title><script src="https://cdn.tailwindcss.com"></script></head><body class="bg-slate-950 text-slate-100 min-h-screen font-sans flex flex-col"><header class="bg-slate-900 border-b border-slate-800 px-4 py-4 flex items-center justify-between"><h1 class="text-xl font-black text-yellow-500 tracking-wider">🐍 ARDA PYDROID IDE</h1><span class="text-xs bg-yellow-500/10 text-yellow-400 border border-yellow-500/20 px-2.5 py-1 rounded-full font-medium">BETA v1.0</span></header><main class="flex-1 max-w-5xl w-full mx-auto p-4 flex flex-col md:flex-row gap-4"><div class="flex-1 flex flex-col bg-slate-900 border border-slate-800 rounded-2xl overflow-hidden shadow-2xl"><div class="bg-slate-850 px-4 py-2 border-b border-slate-800 flex justify-between items-center"><span class="text-xs font-bold text-slate-400">main.py</span><button onclick="koduCalistir()" class="bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold px-4 py-1.5 rounded-lg shadow-md transition-all flex items-center gap-1">▶ ÇALIŞTIR</button></div><textarea id="kodAlani" class="flex-1 w-full min-h-[300px] md:min-h-[450px] bg-slate-950 text-emerald-400 font-mono p-4 focus:outline-none resize-none text-sm md:text-base leading-relaxed">{ornek}</textarea></div><div class="flex-1 flex flex-col bg-slate-900 border border-slate-800 rounded-2xl overflow-hidden shadow-2xl"><div class="bg-slate-850 px-4 py-2 border-b border-slate-800"><span class="text-xs font-bold text-slate-400">Terminal Çıktısı (Console)</span></div><div id="terminal" class="flex-1 w-full min-h-[150px] bg-black text-white font-mono p-4 text-sm whitespace-pre-wrap overflow-y-auto">Kodun çıktısı burada görünecek...</div></div></main><script>function koduCalistir() {{ var kod = document.getElementById("kodAlani").value; var term = document.getElementById("terminal"); term.innerText = "Kod çalıştırılıyor..."; fetch("/run", {{ method: "POST", headers: {{ "Content-Type": "application/x-www-form-urlencoded" }}, body: "code=" + encodeURIComponent(kod) }}).then(r => r.json()).then(d => {{ term.innerText = d.output; }}).catch(e => {{ term.innerText = "Sunucu hatasi!"; }}); }}</script></body></html>"""
@app.route('/run', methods=['POST'])
def kodu_calistir_api():
    code = flask.request.form.get('code', ''); old_out = sys.stdout; new_out = io.StringIO(); sys.stdout = new_out
    try:
        if "import os" in code or "subprocess" in code: out = "Guvenlik Engeli: Sistem dosyalari yasaktir!"
        else: exec(code, {'__builtins__': __builtins__}, {}); out = new_out.getvalue(); out = out if out else "[Kod calisti ama ekrana bir sey yazdirilmadi.]"
    except Exception as e: out = f"HATA OLUŞTU:\n{e}"
    finally: sys.stdout = old_out
    return flask.jsonify({'output': out})
if __name__ == '__main__': app.run(debug=False, host='0.0.0.0', port=10000)
    
